services:
    admin.category:
        class: CategoryBundle\Admin\CategoryAdmin
        arguments: [~, CategoryBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category, group: 'Blog' }

    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }